version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.8
    - 0.11.9
    - 0.8.38
    - 0.8.40
    - 0.8.41
    - 0.8.42
    - 0.8.43
    - 0.8.44
    - 0.8.46
    - 0.8.47
    - 0.8.48
    - 0.8.50
    - 0.8.51
    - 0.8.52
    - 0.8.53
    - 0.8.54
    - 0.8.55
    - 0.8.57
    - 0.9.0
    - 0.9.2
    - 0.9.3
    - 0.9.4
    - 0.9.6
    - 0.9.7
  - dependency-name: rollup-plugin-esbuild
    versions:
    - 3.0.2
    - 4.0.1
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.6
    - 7.30.0
    - 7.30.1
    - 7.30.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
